# Generated by Django 2.1.7 on 2019-03-22 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='drug_period',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('Med_date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=250)),
                ('is_active', models.CharField(max_length=10)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication_drugs',
            fields=[
                ('id', models.AutoField(max_length=250, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=250)),
                ('frequency', models.IntegerField(max_length=1)),
                ('mode_of_administration', models.CharField(max_length=100)),
                ('duration', models.IntegerField(max_length=2)),
                ('quantity', models.IntegerField(max_length=2)),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDose.Medication')),
            ],
        ),
        migrations.CreateModel(
            name='time_period',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('time_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='drug_period',
            name='med_drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDose.Medication_drugs'),
        ),
        migrations.AddField(
            model_name='drug_period',
            name='time_period_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDose.time_period'),
        ),
    ]
