# Generated by Django 2.1.7 on 2019-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDose', '0002_auto_20190408_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
