# Generated by Django 2.1.7 on 2019-04-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDose', '0003_auto_20190411_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time_morning', models.TimeField()),
                ('reminder_time_midday', models.TimeField()),
                ('reminder_time_evening', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='from_diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDose.Medication'),
        ),
    ]
