# Generated by Django 2.1.7 on 2019-04-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDose', '0004_auto_20190412_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='from_med_druds',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MyDose.Medication_drugs'),
            preserve_default=False,
        ),
    ]
