# Generated by Django 2.1.7 on 2019-04-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDose', '0005_reminder_from_med_druds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='from_med_druds',
            new_name='from_med_drugs',
        ),
    ]
